### ISSUE TITLE
Auth required

### ISSUE THREAD

**Issue by steowens** [andris9/smtp-server#1]
I am wondering how an email server can drop e-mail onto a server I implement on top of smtp-server.  How would an email server such as yahoo or godaddy send email to my server if the module demands that they authenticate?  Isn't there a way to accept email from other servers and then check to make sure that the recipient is one whom the system will accept mail on behalf of?

**Comment by hawkfalcon** [comment]
Try adding   
 disabledCommands: ['AUTH'],

**Comment by steowens** [comment]
Awesome Thanks!

**Comment by schnawel007** [comment]
On smtp-connection,js@254 I disabled this function and implemented a check function with onMailFrom and onRcptTo.

**Comment by andris9** [comment]
It is not good practice to do both sending and receiving messages in one server. Better solution would be to start 2 instances. One on port 587 or 465 that requires authentication and handles outgoing emails and another on port 25 that does not require authentication (by setting `disabledCommands: ['AUTH']`) and handles incoming emails.

**Comment by steowens** [comment]
Thanks that sounds like good advice.
