### ISSUE TITLE
TLS exception thrown when dealing with bad client

### ISSUE THREAD

**Issue by sotirosn** [andris9/smtp-server#10]
I will sometimes get this error after the client calls STARTTLS:
```
_tls_wrap.js:133
  if (ctx.context)
         ^
TypeError: Cannot read property 'context' of undefined
  at requestOCSP (_tls_wrap.js:133:10)
  at _tls_wrap.js:185:7
  at loadSNI (_tls_wrap.js:107:12)
  at _tls_wrap.js:182:5
  at loadSession (_tls_wrap.js:100:5)
  at TLSSocket.onclienthello (_tls_wrap.js:164:3)
```
The connection is from the blacklisted [61.240.144.64] ip address, but I need the server to stay up to receive more emails.  What should I do?

**Comment by andris9** [comment]
Do you use any special configuration like SNI with your server?

**Comment by sotirosn** [comment]
No I don't think I am.  I do have virtual hosts setup for http sites but I only host a single https domain and incoming mail domain on port 25.  I did not set my server up with any certificates at all which actually makes me wonder how TLS even works.  Gmail uses STARTTLS and then sends over the mail, but how can it be sure that it is actually talking to my server and not a man in the middle?

The only options I am using are name, banner and `disabledCommands: ['AUTH']`.

By the way thanks for all your great work on this.  I just want a simple server for student email accounts at a small k-8 school so I can sign them up for things like Khan Academy and Google Docs.

**Comment by andris9** [comment]
If you want to disable STARTTLS (enabled by default with self signed certs), you can add it to the disabledCommands list

    disabledCommands: ['AUTH', 'STARTTLS']

What version of Node are you using btw?

**Comment by sotirosn** [comment]
I am using node v0.11.14 with harmony generators.

I wouldn't mind the mail being encrypted while in transit but I don't really expect sensitive information be coming in.  I am surprised other smtp servers accept self-signed certs.  Couldn't you spoof someone's server if you could intercept the packets?

**Comment by andris9** [comment]
Mail exchange on port 25 is supposed to be clear text, so being able to use TLS with self signed certificates it is already a lot better than the default option of not using TLS at all.

**Comment by andris9** [comment]
Could you upgrade to latest v0.12.2 and see if the error still occurs?

**Comment by valeriansaliou** [comment]
+1 on this one, having the same issue when testing w/ https://starttls.info

The server crashes with this stream of errors :

```

```

The issue for me is that, if I disable STARTTLS in the disabled commands list, the server won't be recognized as TLS compatible by SMTP Web testers. Even if I keep the .secure = true version of the server running on port 465, working in pair with the .secure = false version on port 25.
