### ISSUE TITLE
ReferenceError: Set is not defined

### ISSUE THREAD

**Issue by moncasi** [andris9/smtp-server#11]
Hello,
I got an error when creating a new SMTPServer:
ReferenceError: Set is not defined
in lib/smtp-server.js on line 83
And yes, it's not defined... Where does this Set come from ?
Thanks

**Comment by andris9** [comment]
As stated in the README you need Nodejs 0.12 or iojs to run smtp-server. Documentation for Set can be found here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set

**Comment by moncasi** [comment]
Thank You.
I totally missed this line. Sorry for that
