### ISSUE TITLE
ReferenceError: Set is not defined

### ISSUE THREAD

**Issue by ouadi** [andris9/smtp-server#12]
Using version 1.2.0 and above, starting `smtp-server/examples/server.js` fails with:

```javascript
ReferenceError: Set is not defined
    at new SMTPServer (/home/younes.ouadi/Workspace/Dev/Ouzoud/NodeJs/io.ouzoud/node_modules/smtp-server/lib/smtp-server.js:73:28)
```

Versions 1.0.0 to 1.1.1 works fine.

**Comment by andris9** [comment]
Which version of Node are you using? `Set` should be available in Node 0.12.
