### ISSUE TITLE
TypeError: Object is not a function

### ISSUE THREAD

**Issue by alexcotoranu** [andris9/smtp-server#17]
Hi,
This is likely an implementation error, but after installing the npm package, I put the following code near the top of my app.js:

```javascript
var SMTPserver = require('smtp-server');

var server = new SMTPserver({
  name : 'mysmtpserver',
});

server.listen(465);
```

And now get the following error:

![image](https://cloud.githubusercontent.com/assets/12387209/9370927/112c40b2-4689-11e5-84db-a7f094b679f6.png)

**Comment by andris9** [comment]
Use this:

    var SMTPServer = require('smtp-server').SMTPServer;
