### ISSUE TITLE
Malicious clients can cause an unhandled exception

### ISSUE THREAD

**Issue by farmdog** [andris9/smtp-server#20]
In smtp-connection's auth handler, it directly uses network input as a key with an object. If that key does not exist, then undefined will be returned, and immediately bind will be called, resulting in an exception. Can reproduce by:
EHLO localhost
AUTH evil

Causes sasl["sasl_evil"].bind(this) to be executed.

I created a pull request with a possible fix at https://github.com/andris9/smtp-server/pull/19

**Comment by andris9** [comment]
Thanks! I pulled the PR, will put up a new release shortly
