### ISSUE TITLE
Message queued

### ISSUE THREAD

**Issue by zaikin-dunice** [andris9/smtp-server#23]
Hi! 
I have response: '250 Message queued' but don't recieve emails. 
What should I do?

Thanks!

**Comment by andris9** [comment]
"Message queued" is responsed to the client once the message is accepted. It is your own application that needs to hanlde incoming messages. Check the `onData` handler for receiving a message stream: https://github.com/andris9/smtp-server/blob/master/examples/server.js#L83-L94
