### ISSUE TITLE
[Feature Request] Support for bypassing tls/net

### ISSUE THREAD

**Issue by farmdog** [andris9/smtp-server#25]
For a project of mine, I'm planning on using a tunneling proxy to communicate with smtp-server.  In the SMTPServer constructor, there is no option to provide a stream/client connection instead of relying on (tls : net).createServer() to listen for clients.  I don't want this because I want to handle the "socket" connection layer on my own (to provide a tunneling implementation with additional authentication).

Ideally, I’d pass in some object that enables SMTPServer to listen to client connection/disconnection events and integrate that with an outside class that handles listening for and setting up connections.

I’d like to push this back to the repository and make it available, but wanted to see if you had thought about something like this before.  Do you have recommendations on how this should be exposed?

I was thinking of extending options and allowing an object to be passed in with onConnected(id, stream), onDisconnected(id, stream) handlers that could be set.  And then in server.listen, make port optional.  This keeps changes isolated to smtp-server.js.  Lastly, I'd think that an id could be used to correlate SMTP events with the underlying channel; this change would touch multiple files.

Happy to discuss over e-mail if the issue isn’t an appropriate forum.

**Comment by andris9** [comment]
Would it make sense to use the PROXY extension instead? If you set `useProxy` option to `true` then the server expects to be behind a HAProxy load balacer (or any other proxy server that supports [PROXY protocol](http://www.haproxy.org/download/1.5/doc/proxy-protocol.txt) v1)

**Comment by andris9** [comment]
Direct transport uses `localhost` if it fails to detect the current hostname of the server. You can use the `name` property to override it

```javascript
var nodemailer = require('nodemailer');
var directTransport = require('nodemailer-direct-transport');
var transporter = nodemailer.createTransport(directTransport({
    name: 'my-host.example.com'
}));
```

**Comment by farmdog** [comment]
If we use the PROXY extension, we still need to open a socket to a different machine.  Our tunneling will terminate on the same physical machine and do the translation.  
The connection setup would look something like:
[Client] <---- TCP Connection connect/syn/ack ---> [Service Instance 0]
[Client] ---- Proprietary authentication over custom protocol ---> [Service Instance 0]
[Client] ---- SMTP data sent over same channel ---> [Service Instance 0: relay to smtp-server module in proc]
   ...   [Service instance 0:  smtp-server has onConnect, onRcpt events, within those events, a cookie is returned to identify the tcp connection that is proxying that SMTP data to our app logic]

So we need a way to communicate in process with smtp-server; we could use the loopback adapter, but need to tie in the authentication and want to use an existing stream (not socket) to send the information into smtp-server.
