### ISSUE TITLE
How can I test this on my local machine?

### ISSUE THREAD

**Issue by fresheneesz** [andris9/smtp-server#31]
I've been having trouble setting up a server and testing it. I tried setting up a `nodemailer` script, but it doesn't seem to want to send it, or possibly smtp-server doesn't want to receive it. I wrote an SO question that hasn't been getting much love: http://stackoverflow.com/questions/34756908/can-i-send-an-email-from-my-local-machine-to-my-local-machine-using-node-smtp-se

**Comment by andris9** [comment]
Configure nodemailer like this:

```javascript
var transporter = nodemailer.createTransport({host: 'localhost', port: 1025});
```

**Comment by fresheneesz** [comment]
Hmm, I was forwarding 1025 to 25 with iptables - i didn't make that clear. Using that setup does in fact work tho, so thank you! I must be using iptables wrong.
