### ISSUE TITLE
Forwarding?

### ISSUE THREAD

**Issue by stevenvachon** [andris9/smtp-server#35]
Would this require the use of smtp-connection?

**Comment by CHIEFnChowCombo** [comment]
This module only handles incoming, not outgoing.  It would need to be paired with a sender and a transport to do any sort of forwarding, and that would need to be piped in from the `onData` handler.

**Comment by andris9** [comment]
Yes, you would need smtp-connection for this. You could use the incoming stream from smtp-server as the outgoing message for smtp-connection.

```javascript
var server = new SMTPServer({
    onData: function(stream, session, callback){
        // connection is a smtp-connection object
        connection.send({
            from: session.envelope.mailFrom,
            to: session.envelope.rcptTo
        }, stream, function(err, info){
            callback();
        });
    }
});
```

**Comment by stevenvachon** [comment]
@andris9 thanks! One last question: how can the message headers be modified?

**Comment by andris9** [comment]
You can but it would be more complicated. You would have to take the `stream` from smtp-server, parse it as a mime message, replace headers in and pass the modified message to smtp-connection

**Comment by stevenvachon** [comment]
Why so complicated when you suggest adding `Received` manually?

**Comment by andris9** [comment]
If you only want to prepend headers, not modify existing, then you can pipe these through an additional Stream object and write new headers at the beginning

```javascript
var PassThrough = require('stream').PassThrough;
var server = new SMTPServer({
    onData: function(stream, session, callback){
        // connection is a smtp-connection object
       var msgstream = new PassThrough();
       msgstream.write('Received: from zzzzzz\r\n');
       stream.pipe(msgstream);
        connection.send({
            from: session.envelope.mailFrom,
            to: session.envelope.rcptTo
        }, msgstream, function(err, info){
            callback();
        });
    }
});
```

**Comment by stevenvachon** [comment]
Thanks!
