### ISSUE TITLE
[Feature Request]: smtp-server should emit custom events

### ISSUE THREAD

**Issue by CHIEFnChowCombo** [andris9/smtp-server#36]
It would be super useful if I could subscribe to specific events from the server, instead of having to specify callbacks.   As an example, currently, when I want to handle the receipt of message data, I need to pass in an `onData` handler, which winds up creating more tightly coupled code, and restricts the patterns I can use when implementing this modules.  I'd like to be able to register listeners on these events instead, like so:

```javascript
// some-program.js
var mailRelayServer = require("./my-server"); // is an SMTPServer instance

relayServer.on('connection', connectionHandler);
relayServer.on('message', messageHandler1);
relayServer.on('message', messageHandler2);
```

Obviously, there are ways to do what I want without altering this source code, but the utilities gained from what I'm doing on top of this module would potentially be very useful inside this module, and I hate to expand the footprint of the npm world without good reason.

If this is something you've considered, but haven't wanted to implement due to complicating the api, I totally understand.  On the other hand, if it's just a time issue, I'd be happy to submit a PR if the idea is something you'd like to implement.

**Comment by andris9** [comment]
I've used events before but it turned out to be a bit too messy while I'd like to keep smtp-server as simple as possible. I'd suggest you to write a wrapper on top of smtp-server that would add the required behaviour for your specific use case.

**Comment by CHIEFnChowCombo** [comment]
That's the approach i've been taking. No real problem with it, just figured I'd check to see if integrating it was something you felt would provide value to your package. It's why I mentioned the bit about "complicating the api".  It's not too hard to see what you meant by "messy" either. :-)
