### ISSUE TITLE
Could you add XFORWARD support?

### ISSUE THREAD

**Issue by gutschke** [andris9/smtp-server#37]
For use as a Postfix content filter, it would make a lot of sense to support XFORWARD in addition to XCLIENT. I suspect, the code would look extremely similar to what you already had to do for XCLIENT. So, hopefully, this is an easy fix.

**Comment by andris9** [comment]
I'm not sure about this. As far as I understand then XFORWARD doesn't seem to do anything, it's a *for-logging* feature only.

**Comment by gutschke** [comment]
You are correct that XFORWARD is primarily intended for logging purposes; that's doesn't make it useless though. Postfix supports user-provided content filters by piping messages through a sequence of SMTP servers. By design, it can't really make any decisions on the disposition of "EHLO", "MAIL FROM" or "RCPT TO" commands after accepting the message through the very first SMTP server in the pipe line.

But it will make other decisions about message handling throughout the pipeline. These steps can conceivably do varying amounts of logging and benefit from having access to information about the originator.

This means, Postfix passes XFORWARD from stage to stage, but it only accepts incoming XCLIENT; it will never issue XCLIENT for any outgoing connections from the pipeline stages. While I might not necessarily agree with all the implications of this design decision, I understand why it was made and I don't expect Postfix to change this architecture.

So, having the ability to accept XFORWARD (in smtp-server) and to then pass it on to the next stage (in smtp-connection) would be very useful when writing a content filter for Postfix. As is, I lose useful information for no particularly great reason.

Does this make sense? I am only just starting to learn about Postfix's architecture; so, maybe I am not doing a great job at explaining things.

**Comment by andris9** [comment]
Any suggestions what should smtp-server actually do when XFORWARD is issued? For example in case of XCLIENT some session variables are changes (see [here](https://github.com/andris9/smtp-server/blob/187212d26e962c0e7553737666056d16ebee57b4/lib/smtp-connection.js#L590-L619)). In case of XFORWARD this wouldn't happen, so what would? Or is it already good enough if you'd see the XFORWARD command lines in the SMTP transaction log so you would be able to audit?

**Comment by gutschke** [comment]
The XFORWARD spec (or at least the closest thing to an official specification) is here: http://www.postfix.org/XFORWARD_README.html

If I read that correctly, XFORWARD is valid from "MAIL FROM" until "RSET" or "DOT". It is legal to issue XFORWARD multiple times. This sounds as if it follows the same lifetime as the "session" object in smtp-server. So, having a new field in the session object is probably a good solution.

On the other hand, being able to install a listener that gets invoked on XFORWARD would be useful as well.

Also, the server must advertise XFORWARD when it receives EHLO.

And somewhat related, in order to be able to write functioning SMTP proxy, smtp-connection should have a way to issue XFORWARD commands. It might already be ready for that ... I just haven't had time to look at smtp-connection; but you probably would know.

**Comment by andris9** [comment]
I added XFORWARD support in the beta channel

    npm install smtp-server@beta

Both XCLIENT and XFORWARD data is exposed in the session variable, see [server.js](https://github.com/andris9/smtp-server/blob/v1.8/examples/server.js) for a complete example.

```javascript
onMailFrom = function (address, session, callback) {
    // session.xForward is a Map structure
    console.log('XFORWARD ADDR=%s', session.xForward.get('ADDR'));
    callback();
};
```

Could you try it out and see if that is what you would expect from such a feature?

**Comment by gutschke** [comment]
I did a limited amount of testing, but this looks exactly what I need. Thank you! If I do run into additional issues, I'll let you know. But for now it looks as I'm all set.
