### ISSUE TITLE
xtext decoding should probably be done automatically

### ISSUE THREAD

**Issue by gutschke** [andris9/smtp-server#38]
There are a few places in the SMTP protocol (most notably optional arguments to "MAIL FROM:") that are encoded as "xtext". It would be helpful, if they were transparently decoded.

As far as I can tell, decoding is really simple in Node:

    function xtext(s) {
      return s.replace(/[^!-*,-<>-~]/g,
             function(ch) { return encodeURIComponent(ch).replace(/%/g, '+'); });
    }
    
    function xtextDecode(s) {
      return s.replace(/\+[0-9A-F]{2}/g,
             function(ch) { return decodeURIComponent(ch.replace(/\+/g, '%')); });
    }

**Comment by andris9** [comment]
Added xtext decoding 493e77d311a9b584010b3479e7f8c421a0ceef65
