### ISSUE TITLE
Can you add option requireSTARTTLS?

### ISSUE THREAD

**Issue by vkopitsa** [andris9/smtp-server#44]
Hi. I use the smtp-server for the creation of the application and I want to be able to specify the STARTTLS not mandatory.

I know that is hideSTARTTLS, but it hides the STARTTLS in the EHLO

```
EHLO test
250-OK: Nice to meet you [0.0.0.0]
250-PIPELINING
250-8BITMIME
250-SMTPUTF8
250 AUTH PLAIN LOGIN CRAM-MD5
```

Can you add option requireSTARTTLS?

**Comment by andris9** [comment]
STARTTLS is already [required](https://github.com/andris9/smtp-server/blob/master/lib/smtp-connection.js#L836-L839) by default. Authentication is not allowed without first upgrading connection to tls.

**Comment by vkopitsa** [comment]
Yes, but I need use STARTTLS optional, I want to allow use STARTTLS, but only when needed.

**Comment by andris9** [comment]
I added a new option `allowInsecureAuth`. if it set to true, then using STARTTLS is not mandatory

**Comment by vkopitsa** [comment]
Thanks!
