### ISSUE TITLE
Equivalent option to disableDNSValidation?

### ISSUE THREAD

**Issue by djanowski** [andris9/smtp-server#47]
We're using simplesmtp's `disableDNSValidation`. Is there an equivalent if we migrate to `smtp-server`?

**Comment by andris9** [comment]
smtp-server only validates the syntax of email addresses (and isn't strict on this, just some general rules are required), checking dns etc. is on the responsibility of the app developer using the `onMailFrom` method.

**Comment by djanowski** [comment]
Thank you for your feedback.

Are you taking patches on simplesmtp? If not, are you interested in adding a collaborator to address outstanding issues?
