### ISSUE TITLE
MX record forwarding

### ISSUE THREAD

**Issue by corporatepiyush** [andris9/smtp-server#48]
I have to implement a proxy software which will act as MX record relay.
I had a look at Haraka.js which is full fledged framework and found it little bulky.
Can i use this library for the same. 

(Outlook/Thunderbird Mail client) => (local SMTP server) => (:Proxy) => (Remote SMTP server) => ....

:Proxy is what i am trying to implement which will be responsible for doing spam checking, copying the mail body over to RabbitMq and finally relaying it over remote SMTP server.
Is it possible to get MX record as stream so that i can deal with by passing it to  various number of custom middleware  before relaying it over.

**Comment by andris9** [comment]
While Haraka is a full featured SMTP server then this module only provides a basic feature set. You probably could use it as a proxy but in this case you would have to implement the outgoing part yourself. See an example of what smtp-server can do from this [example script](https://github.com/andris9/smtp-server/blob/master/examples/server.js), that's basically everything smtp-server can do, no extra or hidden features..

**Comment by corporatepiyush** [comment]
Thanks
