### ISSUE TITLE
stream value doesn't change

### ISSUE THREAD

**Issue by kubp** [andris9/smtp-server#51]
When I'm parsing email using mailparser I have still the same `mail_object.text` value. I'm sending different emails but output is alway the first email.  Should I add somewhere `mailparser.end()`?

My code:
```
mailparser.on("end", function(mail_object){
  console.log( mail_object.text);
});

...

onData: function(stream, session, callback){
   stream.pipe(mailparser)
   stream.on('end', callback)
}
```

**Comment by andris9** [comment]
Mailparser object is good for one parsing only. Once you have processed one message you should create a new mailparser instance for another
