### ISSUE TITLE
LMTP support

### ISSUE THREAD

**Issue by pilif** [andris9/smtp-server#56]
Would you be interested in a PR that adds LMTP support?

LMTP ([RFC 2033](https://tools.ietf.org/html/rfc2033)) is a stripped down version of SMTP that's used for local mail delivery behind a front end mail server that doesn't want to support local queueing of email but instead wants to just deliver mail.

The protocol is more or less the same as SMTP with three small changes:

1. instead of `HELO`, a client (often an upstream mail server) will send `LHLO`
2. `DATA` is only allowed after at least one `RCPT TO` has been issued.
3. After `DATA`, the server returns one status line for each previously seen `RCPT TO` line.

Is this still within the scope of this project? Would you be interested in a PR?

**Comment by andris9** [comment]
LMTP support would be great  👍

**Comment by andris9** [comment]
I implemented LMTP support myself (v1.11.0). See [example](https://github.com/andris9/smtp-server#using-lmtp)
