### ISSUE TITLE
Promise support

### ISSUE THREAD

**Issue by xpepermint** [andris9/smtp-server#61]
It would be great to have a promise support for `onAuth`, `onMailFrom ` and other `onX` methods out of the box. We could beautify our code by using the async/await syntax (soon in node, babel for now):

```js
var server = new SMTPServer({
    onAuth: async (auth, session, next) {
      let isValid = await db.findUser({id: session.id});
      if (isValid) {
        await next();
      } else {
        throw new Error('not authenticated');
      }
    },
    onError: async (err, next) {
      console.log(err.message);
      await next();
    }
});
```

**Comment by andris9** [comment]
You can easily create a wrapper around smtp-server that would use promises for these calls. I don't use promises internally in the module and I don't want to mess around with generic wrapper as these might fail.
