### ISSUE TITLE
message queued but not received

### ISSUE THREAD

**Issue by start940315** [andris9/smtp-server#68]
I set up a server and it can receive my connection but can not send the mail to my destination.
the session is abnormal:
in onMailFrom(), it is:

```
{ id: 'exboII9SStOa',
remoteAddress: '115.175.24.76',
clientHostname: '[115.175.24.76]',
openingCommand: 'EHLO',
hostNameAppearsAs: '[127.0.0.1]',
xClient: Map {},
xForward: Map {},
transmissionType: 'ESMTPA',
tlsOptions: false,
envelope: 
{ mailFrom: { address: 'startan@squarance.com', args: false },
rcptTo: [] },
transaction: 1,
user: 'squarance' }
```

in onRcptTo(), it is:

```
{ id: 'exboII9SStOa',
remoteAddress: '115.175.24.76',
clientHostname: '[115.175.24.76]',
openingCommand: 'EHLO',
hostNameAppearsAs: '[127.0.0.1]',
xClient: Map {},
xForward: Map {},
transmissionType: 'ESMTPA',
tlsOptions: false,
envelope: { mailFrom: false, rcptTo: [] },
transaction: 2,
user: 'squarance' }
```

the envelope object didn't set the rcptTo and reset mailFrom, why would it happen?

**Comment by andris9** [comment]
Do you have the SMTP logs? Enable the logger option to log SMTP transactions to the console:

```javascript
var server = new SMTPServer({
    ...
    logger: true
});
```

**Comment by pranshu792** [comment]
@andris9 @start940315  I think we could close this issue. People coming to this repo, looks confused by seeing open issues. SMTP servers seems to run perfectly now ! 🎱
