### ISSUE TITLE
hideSize as a option

### ISSUE THREAD

**Issue by pranshu792** [andris9/smtp-server#76]
@andris9 I think we should give a option to hide size feature (optional). As, some clients would not want to reject mails from mail client side. They would like to reject the mails at their end.

**Comment by andris9** [comment]
Could you elaborate a bit? Do you mean like setting a size limit but not displaying the actual limit to the clients?

Currently:

    250-SIZE 12345

Should be:

    250-SIZE

Is this what you mean?

**Comment by pranshu792** [comment]
@andris9 Yes, that's what i mean. Even dont want to show `250-SIZE` in feature list but it should work internally using `stream.sizeExceeded`.

I am not sure if this a relevant feature for other than me. We can put it as optional feature.
Let me know your suggestion on it !

If ok ?  I can raise PR for it : Close this ;)

**Comment by andris9** [comment]
Fixed with e27475c6f6dcc9d52e1e166c3caf095215f9cbbc (published as v1.17.0). Added option `hideSize` that disables actual allowed size from the SIZE extension listing in EHLO. Showing the SIZE extension support is needed to allow the client to use SIZE information in MAIL FROM command.

**Comment by pranshu792** [comment]
Thank you @andris9 :)
