### ISSUE TITLE
CRAM auth

### ISSUE THREAD

**Issue by msimerson** [andris9/smtp-server#8]
> This module does not support CRAM based authentications since these require access to unencrypted user password during the authentication process. You shouldn't store passwords unencrypted anyway, so supporting it doesn't make much sense.

In general I agree. However, anyone wishing to use this module to create a drop-in [MSA](http://en.wikipedia.org/wiki/Mail_submission_agent) to replace their existing one is constrained by the settings of their users MUA. Unfortunately, MUA's tend to remember settings like PLAIN -vs- CRAM-MD5, and if the server suddenly stopped supporting CRAM, then their ability to send mail is suddenly broken.

Would you accept patches that add CRAM support?

**Comment by andris9** [comment]
Generally I do not like CRAM-MD5 at all but I guess it makes sense to support it. One major goal for smtp-server is to be an integration tests server for testing SMTP clients and these might need to support CRAM-MD5 as well. I added CRAM-MD5 and bumped version to v1.3.0. See the docs [here](https://github.com/andris9/smtp-server#cram-md5-authentication)

**Comment by msimerson** [comment]
Thank you!
